auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  "k8s.gcr.io/ingress-nginx/controller:v1.2.0,v1.1.0": "pengyc2019/ingress-nginx"
  "k8s.gcr.io/prometheus-adapter/prometheus-adapter:v0.9.1": "pengyc2019/prometheus-adapter"
  "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.4.2,v2.4.1": "pengyc2019/kube-state-metrics"
  "k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1,v1.1.0": "pengyc2019/kube-webhook-certgen"
