auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  "k8s.gcr.io/ingress-nginx/controller": "pengyc2019/nginx-ingress"
  "k8s.gcr.io/ingress-nginx/controller:v1.3.0": "pengyc2019/nginx-ingress:v1.3.0"
  "k8s.gcr.io/prometheus-adapter/prometheus-adapter": "pengyc2019/prometheus-adapter"
  "k8s.gcr.io/kube-state-metrics/kube-state-metrics": "pengyc2019/kube-state-metrics"
  "k8s.gcr.io/ingress-nginx/kube-webhook-certgen": "pengyc2019/kube-webhook-certgen"
