auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  k8s.gcr.io/ingress-nginx/controller: pengyc2019/ingress-nginx-controller
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: pengyc2019/prometheus-adapter
