auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/metrics-server/metrics-server: pengyc2019/metrics-server
  k8s.gcr.io/ingress-nginx/controller: pengyc2019/ingress-nginx-controller
  k8s.gcr.io/git-sync/git-sync: pengyc2019/git-sync
  gcr.io/kaniko-project/executor:debug,latest: pengyc2019/kaniko-executor
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: pengyc2019/kube-state-metrics
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: pengyc2019/nfs-subdir-external-provisioner
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: pengyc2019/prometheus-adapter
